on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4

      # Install Dependencies
      - name: Install Dependences
        run: npm ci

      # Build
      - name: Build Project
        run: npm run build

      # sync files via FTP
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ${{ env.LOCAL_DIR }}
          server-dir: ${{ env.SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.cache/**
            **/.idea/**
            **/src/**
            **/.gitignore
            **/.prettierignore
            **/.prettierrc
            **/package.json
            **/package-lock.json
            **/README.md